# Generated by Django 5.0.6 on 2026-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_opportunite', models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('PROJET', 'Projet'), ('FINANCEMENT', 'Financement'), ('RECHERCHE', 'Recherche')], max_length=30)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('ARCHIVEE', 'Archivée')], default='ACTIVE', max_length=20)),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='SourceOpportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('type_source', models.CharField(choices=[('SITE_EMPLOI', "Site d'emploi"), ('PORTAIL_PROJET', 'Portail de projets'), ('AUTRE', 'Autre')], max_length=50)),
            ],
        ),
    ]
