# Generated by Django 5.0.6 on 2026-01-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_publiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='opportunities.sourceopportunite'),
        ),
        migrations.AddIndex(
            model_name='opportunite',
            index=models.Index(fields=['type_opportunite', 'statut'], name='opportuniti_type_op_985615_idx'),
        ),
    ]
