# Generated by Django 5.0.6 on 2026-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunite_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunite',
            name='url',
        ),
        migrations.CreateModel(
            name='SimilarityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('PROJET', 'Projet'), ('FINANCEMENT', 'Financement'), ('RECHERCHE', 'Recherche')], max_length=30, unique=True)),
                ('embedding_model', models.CharField(default='default', max_length=200)),
                ('score_min', models.FloatField(default=0.0)),
                ('score_max', models.FloatField(default=1.0)),
                ('score_mean', models.FloatField(default=0.5)),
                ('score_p10', models.FloatField(default=0.3)),
                ('score_p25', models.FloatField(default=0.4)),
                ('score_p50', models.FloatField(default=0.5)),
                ('score_p75', models.FloatField(default=0.6)),
                ('score_p90', models.FloatField(default=0.7)),
                ('sample_count', models.IntegerField(default=0)),
                ('recommended_threshold', models.FloatField(default=0.5)),
                ('minimum_floor', models.FloatField(default=0.35)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('opportunity_type', 'embedding_model')},
            },
        ),
    ]
