# Generated by Django 5.0.6 on 2026-04-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_remove_opportunite_url_similaritymetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawOpportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('raw_titre', models.TextField(blank=True, default='')),
                ('raw_description', models.TextField(blank=True, default='')),
                ('raw_organisation_nom', models.TextField(blank=True, default='')),
                ('raw_type', models.CharField(blank=True, default='', max_length=100)),
                ('raw_status', models.CharField(blank=True, default='', max_length=100)),
                ('raw_date_publication', models.CharField(blank=True, default='', max_length=100)),
                ('raw_date_limite', models.CharField(blank=True, default='', max_length=100)),
                ('source_item_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_listing_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_hash', models.CharField(max_length=40)),
                ('content_fingerprint', models.CharField(blank=True, default='', max_length=40)),
                ('processing_status', models.CharField(choices=[('NEW', 'New'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('MATERIALIZED', 'Materialized')], default='NEW', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_records', to='opportunities.opportunite')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_opportunites', to='opportunities.sourceopportunite')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['payload_hash'], name='raw_opp_payload_hash_idx'), models.Index(fields=['content_fingerprint'], name='raw_opp_content_fp_idx'), models.Index(fields=['processing_status'], name='raw_opp_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rawopportunite',
            constraint=models.UniqueConstraint(condition=models.Q(('source_record_id__isnull', False), models.Q(('source_record_id', ''), _negated=True)), fields=('source', 'source_record_id'), name='uniq_raw_opp_source_record_id'),
        ),
        migrations.AddConstraint(
            model_name='rawopportunite',
            constraint=models.UniqueConstraint(condition=models.Q(('source_item_url__isnull', False), models.Q(('source_item_url', ''), _negated=True)), fields=('source', 'source_item_url'), name='uniq_raw_opp_source_item_url'),
        ),
    ]
