# Generated by Django 5.0.6 on 2026-04-11 10:37

from django.db import migrations, models


def forward_backfill_source_item_url(apps, schema_editor):
    Opportunite = apps.get_model("opportunities", "Opportunite")
    RawOpportunite = apps.get_model("opportunities", "RawOpportunite")
    db_alias = schema_editor.connection.alias

    latest_urls: dict[int, str] = {}
    raw_rows = (
        RawOpportunite.objects.using(db_alias)
        .exclude(canonical_id__isnull=True)
        .exclude(source_item_url__isnull=True)
        .exclude(source_item_url="")
        .values_list("canonical_id", "source_item_url")
        .order_by("-id")
    )

    for canonical_id, source_item_url in raw_rows.iterator(chunk_size=2000):
        if canonical_id not in latest_urls:
            latest_urls[canonical_id] = source_item_url

    if not latest_urls:
        return

    updates = []
    candidates = Opportunite.objects.using(db_alias).filter(pk__in=latest_urls.keys()).only("id", "source_item_url")
    for opportunity in candidates.iterator(chunk_size=1000):
        if opportunity.source_item_url:
            continue

        fallback_url = latest_urls.get(opportunity.pk)
        if not fallback_url:
            continue

        opportunity.source_item_url = fallback_url
        updates.append(opportunity)

        if len(updates) >= 1000:
            Opportunite.objects.using(db_alias).bulk_update(updates, ["source_item_url"], batch_size=1000)
            updates = []

    if updates:
        Opportunite.objects.using(db_alias).bulk_update(updates, ["source_item_url"], batch_size=1000)


def backward_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0014_opportunite_experience_years_opportunite_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='source_item_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.RunPython(forward_backfill_source_item_url, backward_noop),
    ]
