# Generated by Django 5.0.6 on 2026-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_opportunite_source_item_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceopportunite',
            name='type_source',
            field=models.CharField(choices=[('SITE_EMPLOI', "Site d'emploi"), ('SITE_STAGE', 'Site de stage'), ('PORTAIL_PROJET', 'Portail de projets'), ('AUTRE', 'Autre')], max_length=50),
        ),
    ]
