# Generated by Django 5.0.6 on 2026-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0016_alter_sourceopportunite_type_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='contract_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='experience_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='experience_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
