# Generated by Django 5.0.6 on 2026-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0017_opportunite_availability_opportunite_contract_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunite",
            name="company_logo",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="description_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
