# Generated by Django 5.0.6 on 2026-04-12 01:34

from django.conf import settings
from django.db import migrations, models


def deduplicate_source_item_urls(apps, schema_editor):
    Opportunite = apps.get_model('opportunities', 'Opportunite')

    duplicate_groups = (
        Opportunite.objects
        .exclude(source_item_url__isnull=True)
        .exclude(source_item_url='')
        .values('source_id', 'source_item_url')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for group in duplicate_groups.iterator(chunk_size=500):
        duplicates = list(
            Opportunite.objects
            .filter(source_id=group['source_id'], source_item_url=group['source_item_url'])
            .order_by('-quality_score', '-date_modification', '-id')
            .values_list('id', flat=True)
        )
        if len(duplicates) <= 1:
            continue

        # Keep the best-quality row tied to this source URL and archive others.
        Opportunite.objects.filter(id__in=duplicates[1:]).update(
            statut='ARCHIVEE',
            source_item_url=None,
            external_id='',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_opportunite_company_logo_and_description_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunite',
            name='uniq_opp_title_source_pub',
        ),
        migrations.AddField(
            model_name='opportunite',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='type_opportunite',
            field=models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('SAISONNIER', 'Saisonnier'), ('PROJET', 'Projet'), ('FINANCEMENT', 'Financement'), ('RECHERCHE', 'Recherche')], max_length=30),
        ),
        migrations.AlterField(
            model_name='similaritymetrics',
            name='opportunity_type',
            field=models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('SAISONNIER', 'Saisonnier'), ('PROJET', 'Projet'), ('FINANCEMENT', 'Financement'), ('RECHERCHE', 'Recherche')], max_length=30, unique=True),
        ),
        migrations.RunPython(deduplicate_source_item_urls, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='opportunite',
            constraint=models.UniqueConstraint(condition=models.Q(('source_item_url__isnull', False), models.Q(('source_item_url', ''), _negated=True)), fields=('source', 'source_item_url'), name='uniq_opp_source_item_url'),
        ),
    ]
