# Generated by Django 5.0.6 on 2026-04-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0020_opportunite_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
