# Generated by Django 5.0.6 on 2026-04-27

from django.db import migrations, models


def backfill_pipeline_run_totals(apps, schema_editor):
    PipelineRun = apps.get_model("opportunities", "PipelineRun")
    for run in PipelineRun.objects.all().iterator():
        run.total_processed = run.processed_count
        run.total_created = run.created_count
        run.total_updated = run.updated_count
        run.save(update_fields=["total_processed", "total_created", "total_updated"])


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0021_pipelinerun"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="is_stale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="total_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="total_failed_pages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="total_processed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="total_updated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_pipeline_run_totals, migrations.RunPython.noop),
    ]
