# Generated by Django 5.0.6 on 2026-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0031_opportunity_search_vector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Structured ESCO normalization results stored in parallel with legacy skills.'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='Legacy opportunity skill strings captured before ESCO normalization.'),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='skills_normalization_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='skills_normalization_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='skills_normalization_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
