# Generated by Django 5.0.6 on 2026-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0033_opportunite_jobbert_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunite',
            name='normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Reserved structured skill metadata. Kept empty by the current JobBERT/LLM pipeline.'),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='Opportunity skill strings captured for recommendation features.'),
        ),
    ]
