# Generated by Django 5.0.6 on 2026-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0035_opportunity_content_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunite',
            name='type_opportunite',
            field=models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('SAISONNIER', 'Saisonnier'), ('PROJET', 'Calls for tender')], max_length=30),
        ),
        migrations.AlterField(
            model_name='similaritymetrics',
            name='opportunity_type',
            field=models.CharField(choices=[('EMPLOI', 'Emploi'), ('STAGE', 'Stage'), ('SAISONNIER', 'Saisonnier'), ('PROJET', 'Calls for tender')], max_length=30, unique=True),
        ),
    ]
