# Generated by Django 5.0.6 on 2026-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0036_alter_opportunite_type_opportunite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceopportunite',
            name='type_source',
            field=models.CharField(choices=[('SITE_EMPLOI', "Site d'emploi"), ('SITE_STAGE', 'Site de stage'), ('PORTAIL_PROJET', 'Calls for tender portal'), ('AUTRE', 'Autre')], max_length=50),
        ),
    ]
