# Generated by Django 5.0.6 on 2026-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RECOMMANDATION', 'Nouvelle recommandation'), ('RAPPEL_ECHEANCE', "Rappel d'échéance"), ('INFO_SYSTEME', 'Information système'), ('ERREUR_SOURCE', 'Erreur de source')], max_length=30)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
