"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY environment variable is required.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').strip().lower() in ('1', 'true', 'yes', 'on')


def _split_env_list(name, default):
    raw_value = os.getenv(name, '')
    if not raw_value.strip():
        return default
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def _env_flag(name, default=False):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in ('1', 'true', 'yes', 'on')


ALLOWED_HOSTS = _split_env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1','192.168.0.147','172.16.0.141'],
)

ALLOW_ALL_HOSTS_IN_DEBUG = _env_flag('DJANGO_ALLOW_ALL_HOSTS_IN_DEBUG', True)

# Mobile LAN development changes host/IP frequently. Allow all hosts in DEBUG
# to prevent DisallowedHost interruptions while keeping production strict.
if DEBUG and ALLOW_ALL_HOSTS_IN_DEBUG:
    ALLOWED_HOSTS = ['*']

# CORS configuration
CORS_ALLOWED_ORIGINS = _split_env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    [
        "http://localhost:5173",  # Vite dev server
        "http://127.0.0.1:5173",
        "http://localhost:8081",  # Expo web / Metro
        "http://127.0.0.1:8081",
        "http://localhost:19006",  # Expo web classic
        "http://127.0.0.1:19006",
    ],
)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost(?::\d+)?$",
    r"^https?://127\.0\.0\.1(?::\d+)?$",
    r"^https?://10(?:\.\d{1,3}){3}(?::\d+)?$",
    r"^https?://192\.168(?:\.\d{1,3}){2}(?::\d+)?$",
    r"^https?://172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2}(?::\d+)?$",
]

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',

    # Apps métier BidWise
    'users',
    'opportunities',
    'applications',
    'notifications',
]

# Custom user model
AUTH_USER_MODEL = 'users.Utilisateur'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# PostgreSQL Configuration au lieu de SQLite

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Tunis'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_THROTTLE_RATES': {
        'opportunity_similar': '20/min',

        # OTP endpoints (configurable via env)
        'otp_request': os.getenv('OTP_REQUEST_RATE', '10/hour'),
        'otp_verify': os.getenv('OTP_VERIFY_RATE', '20/hour'),
        'otp_verify_email': os.getenv('OTP_VERIFY_EMAIL_RATE', '10/hour'),

        # Public Google auth endpoint
        'google_auth': os.getenv('GOOGLE_AUTH_RATE', '60/hour'),
    },

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
# Email Configuration
# Strategy: try Gmail SMTP → Console fallback
_GMAIL_APP_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '').strip()
_GMAIL_ADDRESS = os.getenv('GMAIL_ADDRESS', '').strip()

if  _GMAIL_APP_PASSWORD and _GMAIL_ADDRESS:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = _GMAIL_ADDRESS
    EMAIL_HOST_PASSWORD = _GMAIL_APP_PASSWORD
    DEFAULT_FROM_EMAIL = f'BidWise <{_GMAIL_ADDRESS}>'
else:
    # Option C: Console (local development)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@bidwise.com'

# Google OAuth2
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# Embeddings
OPPORTUNITY_EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
OPPORTUNITY_EMBEDDING_BATCH_SIZE = int(os.getenv("OPPORTUNITY_EMBEDDING_BATCH_SIZE", "32"))
OPPORTUNITY_EMBEDDING_MODEL_VERSION = "prod-v1-fr"

# Optional pgvector acceleration for similarity search. Keep disabled by default
# to preserve current Python cosine behavior until rollout is explicitly enabled.
OPPORTUNITY_PGVECTOR_ENABLED = os.getenv("OPPORTUNITY_PGVECTOR_ENABLED", "false").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
OPPORTUNITY_PGVECTOR_DIMENSIONS = int(os.getenv("OPPORTUNITY_PGVECTOR_DIMENSIONS", "384"))
