"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY environment variable is required.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').strip().lower() in ('1', 'true', 'yes', 'on')


def _split_env_list(name, default):
    raw_value = os.getenv(name, '')
    if not raw_value.strip():
        return default
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def _env_flag(name, default=False):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in ('1', 'true', 'yes', 'on')


ALLOWED_HOSTS = _split_env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1','192.168.0.147','172.16.0.141'],
)

ALLOW_ALL_HOSTS_IN_DEBUG = _env_flag('DJANGO_ALLOW_ALL_HOSTS_IN_DEBUG', True)

# Mobile LAN development changes host/IP frequently. Allow all hosts in DEBUG
# to prevent DisallowedHost interruptions while keeping production strict.
if DEBUG and ALLOW_ALL_HOSTS_IN_DEBUG:
    ALLOWED_HOSTS = ['*']

# CORS configuration
CORS_ALLOWED_ORIGINS = _split_env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    [
        "http://localhost:5173",  # Vite dev server
        "http://127.0.0.1:5173",
        "http://localhost:8081",  # Expo web / Metro
        "http://127.0.0.1:8081",
        "http://localhost:19006",  # Expo web classic
        "http://127.0.0.1:19006",
    ],
)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost(?::\d+)?$",
    r"^https?://127\.0\.0\.1(?::\d+)?$",
    r"^https?://10(?:\.\d{1,3}){3}(?::\d+)?$",
    r"^https?://192\.168(?:\.\d{1,3}){2}(?::\d+)?$",
    r"^https?://172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2}(?::\d+)?$",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = _split_env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    CORS_ALLOWED_ORIGINS,
)


# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'ai.apps.AIConfig',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'django_celery_beat',

    # Apps métier BidWise
    'users',
    'opportunities',
    'applications',
    'notifications',
]

# Custom user model
AUTH_USER_MODEL = 'users.Utilisateur'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# PostgreSQL Configuration au lieu de SQLite

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Tunis'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Resume storage
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "").strip()
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "").strip()
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "").strip()
CLOUDINARY_SECURE = _env_flag("CLOUDINARY_SECURE", True)
_CLOUDINARY_RESUME_CONFIGURED = all(
    (
        CLOUDINARY_CLOUD_NAME,
        CLOUDINARY_API_KEY,
        CLOUDINARY_API_SECRET,
    )
)
PROFILE_RESUME_USE_CLOUDINARY = _env_flag(
    "PROFILE_RESUME_USE_CLOUDINARY",
    _CLOUDINARY_RESUME_CONFIGURED,
)
if PROFILE_RESUME_USE_CLOUDINARY and not _CLOUDINARY_RESUME_CONFIGURED:
    raise ImproperlyConfigured(
        "PROFILE_RESUME_USE_CLOUDINARY is enabled, but Cloudinary credentials are incomplete."
    )

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_THROTTLE_RATES': {
        'opportunity_similar': '20/min',

        # OTP endpoints (configurable via env)
        'otp_request': os.getenv('OTP_REQUEST_RATE', '10/hour'),
        'otp_verify': os.getenv('OTP_VERIFY_RATE', '20/hour'),
        'otp_verify_email': os.getenv('OTP_VERIFY_EMAIL_RATE', '10/hour'),

        # Public Google auth endpoint
        'google_auth': os.getenv('GOOGLE_AUTH_RATE', '60/hour'),

        # Authenticated profile autocomplete endpoints
        'profile_suggestions': os.getenv('PROFILE_SUGGESTIONS_RATE', '120/min'),
        'resume_match_ai': '5/min',
    },

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
# Email Configuration
# Strategy: try Gmail SMTP → Console fallback
_GMAIL_APP_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '').strip()
_GMAIL_ADDRESS = os.getenv('GMAIL_ADDRESS', '').strip()

if  _GMAIL_APP_PASSWORD and _GMAIL_ADDRESS:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = _GMAIL_ADDRESS
    EMAIL_HOST_PASSWORD = _GMAIL_APP_PASSWORD
    DEFAULT_FROM_EMAIL = f'BidWise <{_GMAIL_ADDRESS}>'
else:
    # Option C: Console (local development)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@bidwise.com'

# Google OAuth2
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# Embeddings
OPPORTUNITY_EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
OPPORTUNITY_EMBEDDING_BATCH_SIZE = int(os.getenv("OPPORTUNITY_EMBEDDING_BATCH_SIZE", "32"))
OPPORTUNITY_EMBEDDING_MODEL_VERSION = "prod-v1-fr"
OPPORTUNITY_EMBEDDING_TASK_LIMIT = int(os.getenv("OPPORTUNITY_EMBEDDING_TASK_LIMIT", "200"))
OPPORTUNITY_INLINE_EMBEDDINGS_ENABLED = os.getenv(
    "OPPORTUNITY_INLINE_EMBEDDINGS_ENABLED",
    "false",
).strip().lower() in ("1", "true", "yes", "on")

# Optional pgvector acceleration for opportunity similarity and AI recommendation
# retrieval. Enabled by default because production opportunity embeddings are
# materialized; disable only to force bounded fallback behavior during incidents.
OPPORTUNITY_PGVECTOR_ENABLED = os.getenv("OPPORTUNITY_PGVECTOR_ENABLED", "true").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
OPPORTUNITY_PGVECTOR_DIMENSIONS = int(os.getenv("OPPORTUNITY_PGVECTOR_DIMENSIONS", "384"))

# CrossEncoder reranking. Disabled by default for deadline stability unless the
# model is explicitly shipped in the local HuggingFace cache.
CROSS_ENCODER_ENABLED = _env_flag("CROSS_ENCODER_ENABLED", True)
CROSS_ENCODER_MODEL = os.getenv(
    "CROSS_ENCODER_MODEL",
    "cross-encoder/ms-marco-MiniLM-L-6-v2",
)
CROSS_ENCODER_MAX_CANDIDATES = int(os.getenv("CROSS_ENCODER_MAX_CANDIDATES", "15"))
CROSS_ENCODER_WEIGHT = float(os.getenv("CROSS_ENCODER_WEIGHT", "0.25"))
CROSS_ENCODER_BATCH_SIZE = int(os.getenv("CROSS_ENCODER_BATCH_SIZE", "8"))
CROSS_ENCODER_TIMEOUT_SECONDS = float(os.getenv("CROSS_ENCODER_TIMEOUT_SECONDS", "8.0"))
CROSS_ENCODER_MAX_TEXT_CHARS = int(os.getenv("CROSS_ENCODER_MAX_TEXT_CHARS", "2400"))
CROSS_ENCODER_REASON_THRESHOLD = float(os.getenv("CROSS_ENCODER_REASON_THRESHOLD", "0.82"))
CROSS_ENCODER_LOCAL_FILES_ONLY = _env_flag("CROSS_ENCODER_LOCAL_FILES_ONLY", True)
CROSS_ENCODER_UNAVAILABLE_TTL_SECONDS = int(os.getenv("CROSS_ENCODER_UNAVAILABLE_TTL_SECONDS", "300"))

# Local job-domain semantic reranking. Disabled by default so the product stays
# fast unless the model has been downloaded and the feature is explicitly tested.
JOBBERT_RERANK_ENABLED = _env_flag("JOBBERT_RERANK_ENABLED", False)
JOBBERT_ALLOW_LIVE_FALLBACK = _env_flag("JOBBERT_ALLOW_LIVE_FALLBACK", False)
JOBBERT_MODEL = os.getenv("JOBBERT_MODEL", "TechWolf/JobBERT-v3")
JOBBERT_MAX_CANDIDATES = int(os.getenv("JOBBERT_MAX_CANDIDATES", "20"))
JOBBERT_BATCH_SIZE = int(os.getenv("JOBBERT_BATCH_SIZE", "16"))
JOBBERT_MAX_TEXT_CHARS = int(os.getenv("JOBBERT_MAX_TEXT_CHARS", "2200"))
JOBBERT_TIMEOUT_SECONDS = float(os.getenv("JOBBERT_TIMEOUT_SECONDS", "12.0"))
JOBBERT_HIGH_THRESHOLD = float(os.getenv("JOBBERT_HIGH_THRESHOLD", "0.65"))
JOBBERT_MEDIUM_THRESHOLD = float(os.getenv("JOBBERT_MEDIUM_THRESHOLD", "0.55"))
JOBBERT_WEAK_THRESHOLD = float(os.getenv("JOBBERT_WEAK_THRESHOLD", "0.45"))
JOBBERT_HIGH_BONUS = float(os.getenv("JOBBERT_HIGH_BONUS", "0.08"))
JOBBERT_MEDIUM_BONUS = float(os.getenv("JOBBERT_MEDIUM_BONUS", "0.04"))
JOBBERT_WEAK_PENALTY = float(os.getenv("JOBBERT_WEAK_PENALTY", "0.04"))

# Optional request-time LLM hierarchy validation. Disabled by default and limited
# to top recommendations already selected by JobBERT and deterministic rules.
RECOMMENDATION_LLM_HIERARCHY_ENABLED = _env_flag("RECOMMENDATION_LLM_HIERARCHY_ENABLED", False)
RECOMMENDATION_LLM_HIERARCHY_TOP_N = int(os.getenv("RECOMMENDATION_LLM_HIERARCHY_TOP_N", "10"))
RECOMMENDATION_LLM_HIERARCHY_MIN_SCORE = float(os.getenv("RECOMMENDATION_LLM_HIERARCHY_MIN_SCORE", "0.60"))

# Optional LLM enrichment and validation providers.
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "gemini").strip().lower()
LLM_ENRICHMENT_ENABLED = _env_flag("LLM_ENRICHMENT_ENABLED", False)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_FALLBACK_MODELS = os.getenv("GEMINI_FALLBACK_MODELS", "")
GEMINI_API_BASE_URL = os.getenv(
    "GEMINI_API_BASE_URL",
    "https://generativelanguage.googleapis.com/v1beta",
).rstrip("/")
GEMINI_TIMEOUT_SECONDS = float(os.getenv("GEMINI_TIMEOUT_SECONDS", "20.0"))
GEMINI_TEMPERATURE = float(os.getenv("GEMINI_TEMPERATURE", "0.1"))
GEMINI_MAX_OUTPUT_TOKENS = int(os.getenv("GEMINI_MAX_OUTPUT_TOKENS", "4000"))
LLM_PROVIDER_MAX_RETRIES = int(os.getenv("LLM_PROVIDER_MAX_RETRIES", "1"))
LLM_PROVIDER_RETRY_DELAY_SECONDS = float(os.getenv("LLM_PROVIDER_RETRY_DELAY_SECONDS", "5.0"))
LLM_PROVIDER_RETRY_BACKOFF_FACTOR = float(os.getenv("LLM_PROVIDER_RETRY_BACKOFF_FACTOR", "2.0"))
OLLAMA_FALLBACK_ENABLED = _env_flag("OLLAMA_FALLBACK_ENABLED", False)
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://host.docker.internal:11434").rstrip("/")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:7b-instruct")
OLLAMA_TIMEOUT_SECONDS = float(os.getenv("OLLAMA_TIMEOUT_SECONDS", "45.0"))
OLLAMA_TEMPERATURE = float(os.getenv("OLLAMA_TEMPERATURE", "0.0"))
OLLAMA_MAX_OUTPUT_TOKENS = int(os.getenv("OLLAMA_MAX_OUTPUT_TOKENS", "1200"))
OLLAMA_KEEP_ALIVE = os.getenv("OLLAMA_KEEP_ALIVE", "").strip()

# Celery / scheduled opportunity pipeline
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
DJANGO_CACHE_URL = os.getenv("DJANGO_CACHE_URL", "redis://redis:6379/1")
OPPORTUNITY_FACET_CACHE_TTL_SECONDS = int(os.getenv("OPPORTUNITY_FACET_CACHE_TTL_SECONDS", "60"))
OPPORTUNITY_FACET_CACHE_VERSION = os.getenv("OPPORTUNITY_FACET_CACHE_VERSION", "v1")
OPPORTUNITY_SLOW_QUERY_MS = float(os.getenv("OPPORTUNITY_SLOW_QUERY_MS", "250"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": DJANGO_CACHE_URL,
    }
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_ROUTES = {
    # User-facing profile tasks must not wait behind scraping or opportunity
    # enrichment batches. They are consumed by the dedicated celery_profile
    # worker in docker-compose.yml.
    "users.parse_profile_resume": {"queue": "profile_resume"},
    "users.generate_profile_embedding": {"queue": "profile_resume"},
    # LLM opportunity backfills can be slow with local Ollama. Keep them off the
    # main scraping/materialization queue so source collection stays responsive.
    "ai.enrich_opportunity_llm_backfill": {"queue": "opportunity_enrichment"},
    "ai.enrich_opportunity_with_llm": {"queue": "opportunity_enrichment"},
}
PROFILE_RESUME_TASK_SOFT_TIME_LIMIT_SECONDS = int(
    os.getenv("PROFILE_RESUME_TASK_SOFT_TIME_LIMIT_SECONDS", "150")
)
PROFILE_RESUME_TASK_TIME_LIMIT_SECONDS = int(
    os.getenv("PROFILE_RESUME_TASK_TIME_LIMIT_SECONDS", "180")
)
PROFILE_RESUME_REALTIME_USE_MODEL = _env_flag("PROFILE_RESUME_REALTIME_USE_MODEL", False)
PROFILE_RESUME_REALTIME_ALLOW_SEMANTIC_MAPPING = _env_flag(
    "PROFILE_RESUME_REALTIME_ALLOW_SEMANTIC_MAPPING",
    False,
)
PROFILE_RESUME_REALTIME_USE_LLM = _env_flag("PROFILE_RESUME_REALTIME_USE_LLM", False)
PROFILE_RESUME_REALTIME_NORMALIZE_SKILLS = _env_flag(
    "PROFILE_RESUME_REALTIME_NORMALIZE_SKILLS",
    False,
)
PROFILE_RESUME_STRUCTURED_LLM_ENABLED = _env_flag(
    "PROFILE_RESUME_STRUCTURED_LLM_ENABLED",
    True,
)
PROFILE_RESUME_STRUCTURED_LLM_FALLBACK_ENABLED = _env_flag(
    "PROFILE_RESUME_STRUCTURED_LLM_FALLBACK_ENABLED",
    False,
)
PROFILE_RESUME_QWEN_MODEL = os.getenv("PROFILE_RESUME_QWEN_MODEL", OLLAMA_MODEL).strip()
PROFILE_RESUME_QWEN_TIMEOUT_SECONDS = float(os.getenv("PROFILE_RESUME_QWEN_TIMEOUT_SECONDS", "180"))
PROFILE_RESUME_QWEN_TEMPERATURE = float(os.getenv("PROFILE_RESUME_QWEN_TEMPERATURE", "0.0"))
PROFILE_RESUME_QWEN_MAX_TOKENS = int(os.getenv("PROFILE_RESUME_QWEN_MAX_TOKENS", "300"))
PROFILE_RESUME_QWEN_TEXT_CHARS = int(os.getenv("PROFILE_RESUME_QWEN_TEXT_CHARS", "1200"))
PROFILE_RESUME_QWEN_KEEP_ALIVE = os.getenv("PROFILE_RESUME_QWEN_KEEP_ALIVE", "30m").strip()
PROFILE_FEATURES_USE_RESUME_NORMALIZED_SKILLS = _env_flag(
    "PROFILE_FEATURES_USE_RESUME_NORMALIZED_SKILLS",
    False,
)
OPPORTUNITY_LLM_BACKFILL_ENABLED = _env_flag("OPPORTUNITY_LLM_BACKFILL_ENABLED", True)
OPPORTUNITY_LLM_BACKFILL_SOURCE = os.getenv("OPPORTUNITY_LLM_BACKFILL_SOURCE", "all").strip()
OPPORTUNITY_LLM_BACKFILL_LIMIT = int(os.getenv("OPPORTUNITY_LLM_BACKFILL_LIMIT", "5"))
OPPORTUNITY_LLM_BACKFILL_MIN_DESCRIPTION_CHARS = int(
    os.getenv("OPPORTUNITY_LLM_BACKFILL_MIN_DESCRIPTION_CHARS", "1000")
)
OPPORTUNITY_LLM_BACKFILL_DELAY_SECONDS = float(os.getenv("OPPORTUNITY_LLM_BACKFILL_DELAY_SECONDS", "2.0"))
OPPORTUNITY_LLM_BACKFILL_WORKERS = int(os.getenv("OPPORTUNITY_LLM_BACKFILL_WORKERS", "1"))
OPPORTUNITY_LLM_BACKFILL_LOCK_SECONDS = int(os.getenv("OPPORTUNITY_LLM_BACKFILL_LOCK_SECONDS", str(60 * 30)))
OPPORTUNITY_LLM_BACKFILL_CRON_MINUTE = os.getenv("OPPORTUNITY_LLM_BACKFILL_CRON_MINUTE", "7,37")
CELERY_BEAT_SCHEDULER = os.getenv(
    "CELERY_BEAT_SCHEDULER",
    "celery.beat:PersistentScheduler",
)
CELERY_BEAT_SCHEDULE = {
    "dispatch-opportunity-pipeline-every-15-minutes": {
        "task": "opportunities.collect_opportunities",
        "schedule": crontab(minute="*/15"),
    },
    "monitor-opportunity-pipeline-every-15-minutes": {
        "task": "opportunities.monitor_pipeline",
        "schedule": crontab(minute="*/15"),
    },
}
if OPPORTUNITY_LLM_BACKFILL_ENABLED:
    CELERY_BEAT_SCHEDULE["enrich-opportunity-llm-backfill"] = {
        "task": "ai.enrich_opportunity_llm_backfill",
        "schedule": crontab(minute=OPPORTUNITY_LLM_BACKFILL_CRON_MINUTE),
    }

OPPORTUNITY_SCHEDULER_BEAT_INTERVAL_SECONDS = int(
    os.getenv("OPPORTUNITY_SCHEDULER_BEAT_INTERVAL_SECONDS", str(15 * 60))
)
OPPORTUNITY_SCHEDULER_DECISION_CACHE_TIMEOUT_SECONDS = int(
    os.getenv(
        "OPPORTUNITY_SCHEDULER_DECISION_CACHE_TIMEOUT_SECONDS",
        str(2 * OPPORTUNITY_SCHEDULER_BEAT_INTERVAL_SECONDS),
    )
)
OPPORTUNITY_SCHEDULER_MAX_SOURCES_PER_TICK = int(
    os.getenv("OPPORTUNITY_SCHEDULER_MAX_SOURCES_PER_TICK", "0")
)
OPPORTUNITY_SCHEDULER_DISPATCH_DEDUP_SECONDS = int(
    os.getenv("OPPORTUNITY_SCHEDULER_DISPATCH_DEDUP_SECONDS", str(5 * 60))
)
OPPORTUNITY_SCHEDULER_SCORE_HISTORY_LIMIT = int(
    os.getenv("OPPORTUNITY_SCHEDULER_SCORE_HISTORY_LIMIT", "10")
)

OPPORTUNITY_PIPELINE_SOURCES = ["keejob", "linkedin", "marches_publics", "emploi_tn"]
SOURCE_CONFIG = {
    "linkedin": {
        "priority": 1,
        "schedule_seconds": int(os.getenv("LINKEDIN_SCHEDULE_SECONDS", str(60 * 60))),
        "stale_schedule_seconds": int(os.getenv("LINKEDIN_STALE_SCHEDULE_SECONDS", str(15 * 60))),
        "failure_retry_seconds": int(os.getenv("LINKEDIN_FAILURE_RETRY_SECONDS", str(15 * 60))),
        "stale_after_seconds": int(os.getenv("LINKEDIN_STALE_AFTER_SECONDS", str(12 * 60 * 60))),
        "max_duration_seconds": int(os.getenv("LINKEDIN_MAX_DURATION_SECONDS", str(10 * 60))),
    },
    "keejob": {
        "priority": 2,
        "schedule_seconds": int(os.getenv("KEEJOB_SCHEDULE_SECONDS", str(2 * 60 * 60))),
        "stale_schedule_seconds": int(os.getenv("KEEJOB_STALE_SCHEDULE_SECONDS", str(30 * 60))),
        "failure_retry_seconds": int(os.getenv("KEEJOB_FAILURE_RETRY_SECONDS", str(30 * 60))),
        "stale_after_seconds": int(os.getenv("KEEJOB_STALE_AFTER_SECONDS", str(12 * 60 * 60))),
        "max_duration_seconds": int(os.getenv("KEEJOB_MAX_DURATION_SECONDS", str(20 * 60))),
    },
    "emploi_tn": {
        "priority": 3,
        "schedule_seconds": int(os.getenv("EMPLOI_TN_SCHEDULE_SECONDS", str(6 * 60 * 60))),
        "stale_schedule_seconds": int(os.getenv("EMPLOI_TN_STALE_SCHEDULE_SECONDS", str(60 * 60))),
        "failure_retry_seconds": int(os.getenv("EMPLOI_TN_FAILURE_RETRY_SECONDS", str(60 * 60))),
        "stale_after_seconds": int(os.getenv("EMPLOI_TN_STALE_AFTER_SECONDS", str(24 * 60 * 60))),
        "max_duration_seconds": int(os.getenv("EMPLOI_TN_MAX_DURATION_SECONDS", str(20 * 60))),
    },
    "marches_publics": {
        "priority": 4,
        "schedule_seconds": int(os.getenv("MARCHES_PUBLICS_SCHEDULE_SECONDS", str(12 * 60 * 60))),
        "stale_schedule_seconds": int(os.getenv("MARCHES_PUBLICS_STALE_SCHEDULE_SECONDS", str(2 * 60 * 60))),
        "failure_retry_seconds": int(os.getenv("MARCHES_PUBLICS_FAILURE_RETRY_SECONDS", str(2 * 60 * 60))),
        "stale_after_seconds": int(os.getenv("MARCHES_PUBLICS_STALE_AFTER_SECONDS", str(48 * 60 * 60))),
        "max_duration_seconds": int(os.getenv("MARCHES_PUBLICS_MAX_DURATION_SECONDS", str(30 * 60))),
    },
}
OPPORTUNITY_SOURCE_CONFIG = SOURCE_CONFIG
SCRAPER_CONFIG = {
    "linkedin": {
        "delay": (1, 2),
        "max_pages": 100,
        "max_empty_pages": 2,
        "max_failures": 3,
        "fetch_details": os.getenv("LINKEDIN_FETCH_DETAILS", "1").lower() in {"1", "true", "yes", "on"},
    },
    "keejob": {"delay": (0.5, 1.5), "max_pages": 1000, "max_empty_pages": 2},
    "marches_publics": {"delay": (1, 2), "max_pages": 1000, "max_empty_pages": 2},
    "emploi_tn": {"delay": (3, 6), "max_pages": 1000, "max_empty_pages": 2},
}
OPPORTUNITY_PIPELINE_SCHEDULE_SECONDS = int(
    os.getenv("OPPORTUNITY_PIPELINE_SCHEDULE_SECONDS", str(6 * 60 * 60))
)
OPPORTUNITY_PIPELINE_LOCK_KEY = os.getenv(
    "OPPORTUNITY_PIPELINE_LOCK_KEY",
    "opportunities:collect_opportunities:lock",
)
OPPORTUNITY_PIPELINE_LOCK_TIMEOUT = 3600
OPPORTUNITY_PIPELINE_LOCK_REDIS_URL = os.getenv("OPPORTUNITY_PIPELINE_LOCK_REDIS_URL", REDIS_URL)
OPPORTUNITY_ALERTS_ENABLED = _env_flag("OPPORTUNITY_ALERTS_ENABLED", True)
OPPORTUNITY_ALERT_DISCORD_WEBHOOK_URL = os.getenv("OPPORTUNITY_ALERT_DISCORD_WEBHOOK_URL", "").strip()
OPPORTUNITY_ALERT_FAILURE_THRESHOLD = int(os.getenv("OPPORTUNITY_ALERT_FAILURE_THRESHOLD", "3"))
OPPORTUNITY_ALERT_COOLDOWN_SECONDS = int(os.getenv("OPPORTUNITY_ALERT_COOLDOWN_SECONDS", str(60 * 60)))
OPPORTUNITY_ALERT_STATE_TTL_SECONDS = int(os.getenv("OPPORTUNITY_ALERT_STATE_TTL_SECONDS", str(7 * 24 * 60 * 60)))
OPPORTUNITY_ALERT_REQUEST_TIMEOUT_SECONDS = float(
    os.getenv("OPPORTUNITY_ALERT_REQUEST_TIMEOUT_SECONDS", "5.0")
)
OPPORTUNITY_PIPELINE_STUCK_SECONDS = int(os.getenv("OPPORTUNITY_PIPELINE_STUCK_SECONDS", str(2 * 60 * 60)))
OPPORTUNITY_AUTO_RECOVERY_ENABLED = _env_flag("OPPORTUNITY_AUTO_RECOVERY_ENABLED", True)
ADMIN_DASHBOARD_CELERY_INSPECT_TIMEOUT = float(
    os.getenv("ADMIN_DASHBOARD_CELERY_INSPECT_TIMEOUT", "2.0")
)
