

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: bidwise_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOGLE_CLIENT_ID=149784459020-aknnq7m4rlur7pj32cd1elkf68cpbblt.apps.googleusercontent.com
      - GMAIL_ADDRESS=hibabelg7@gmail.com
      - GMAIL_APP_PASSWORD=qgih nctp mvtr ykfc
  db:
    image: postgres:16
    container_name: bidwise_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bidwise_db
      POSTGRES_USER: bidwise_user
      POSTGRES_PASSWORD: bidwise_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bidwise_user -d bidwise_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
