# Generated by Django 5.0.6 on 2026-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VUE', 'Vue'), ('INTERESSEE', 'Intéressée'), ('POSTULEE_EXTERNEMENT', 'Postulée (site externe)'), ('ABANDONNEE', 'Abandonnée')], default='VUE', max_length=30)),
                ('url_source', models.URLField(blank=True, help_text='Lien vers la page externe de candidature', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CV', 'CV'), ('LETTRE', 'Lettre de motivation'), ('DOSSIER', 'Dossier de projet'), ('AUTRE', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
