# Generated by Django 5.0.6 on 2026-01-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidature',
            name='opportunite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='opportunities.opportunite'),
        ),
        migrations.AddField(
            model_name='document',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.candidature'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('candidat', 'opportunite')},
        ),
    ]
