# Generated by Django 5.0.6 on 2026-06-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_internal_application_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="url_source",
            field=models.URLField(
                blank=True,
                help_text="Lien vers la page externe de candidature",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("CV", "CV"),
                    ("LETTRE", "Lettre de motivation"),
                    ("DOSSIER", "Dossier de projet"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
            ),
        ),
    ]
