"""Canonical skill keywords used by NLP extraction."""

SKILLS = [
    "python",
    "java",
    "scala",
    "sql",
    "excel",
    "tcd",
    "power bi",
    "django",
    "react",
    "node",
    "aws",
    "azure",
    "gcp",
    "bigquery",
    "snowflake",
    "redshift",
    "airflow",
    "spark",
    "dbt",
    "etl",
    "elt",
    "docker",
    "sage",
    "sap",
    "linux",
    "windows",
    "kali linux",
    "burp suite",
    "metasploit",
    "wireshark",
    "tcp ip",
    "dns",
    "http",
    "vpn",
    "ceh",
    "oscp",
    "github",
    "jira",
    "confluence",
    "ms project",
    "bpf",
    "controle qualite",
    "contrôle qualité",
    "procedures qualite",
    "procédures qualité",
    "prelevement",
    "prélèvement",
    "etiquetage",
    "étiquetage",
]
