# Generated by Django 5.0.6 on 2026-05-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESCOOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('preferred_label', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('isco_group', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_labels', models.JSONField(default=list)),
                ('related_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['preferred_label'], name='ai_escooccu_preferr_8bd71a_idx'), models.Index(fields=['family'], name='ai_escooccu_family_cb0b72_idx'), models.Index(fields=['isco_group'], name='ai_escooccu_isco_gr_915c1b_idx')],
            },
        ),
    ]
