# Generated by Django 5.0.6 on 2026-05-14 11:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ESCOSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('preferred_label', models.CharField(max_length=255)),
                ('alt_labels', models.JSONField(default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['preferred_label', 'uri'],
                'indexes': [models.Index(fields=['preferred_label'], name='ai_escoskil_preferr_337cf4_idx')],
            },
        ),
    ]
