# Generated by Django 5.0.6 on 2026-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_escoskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='escoskill',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='embedding_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='escoskill',
            index=models.Index(fields=['embedding_model', 'embedding_version'], name='ai_escoskil_embeddi_91be34_idx'),
        ),
        migrations.AddIndex(
            model_name='escoskill',
            index=models.Index(fields=['embedding_dimensions'], name='ai_escoskil_embeddi_e8e062_idx'),
        ),
    ]
