# Generated by Django 5.0.6 on 2026-05-14 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_escoskill_embedding_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCOOccupationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('preferred_label_en', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_label_fr', models.CharField(blank=True, default='', max_length=255)),
                ('alt_labels_en', models.JSONField(blank=True, default=list)),
                ('alt_labels_fr', models.JSONField(blank=True, default=list)),
                ('hidden_labels_en', models.JSONField(blank=True, default=list)),
                ('hidden_labels_fr', models.JSONField(blank=True, default=list)),
                ('search_text_multilingual', models.TextField(blank=True, default='')),
                ('isco_group', models.CharField(blank=True, default='', max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('nace_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['preferred_label_en', 'preferred_label_fr', 'uri'],
            },
        ),
        migrations.CreateModel(
            name='ESCOOccupationSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['occupation_id', 'skill_id', 'relation_type'],
            },
        ),
        migrations.AddField(
            model_name='escoskill',
            name='alt_labels_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='alt_labels_fr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='hidden_labels_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='hidden_labels_fr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='preferred_label_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='preferred_label_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='escoskill',
            name='search_text_multilingual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='escoskill',
            index=models.Index(fields=['preferred_label_en'], name='ai_escoskil_preferr_f6f343_idx'),
        ),
        migrations.AddIndex(
            model_name='escoskill',
            index=models.Index(fields=['preferred_label_fr'], name='ai_escoskil_preferr_4a59c6_idx'),
        ),
        migrations.AddIndex(
            model_name='escooccupationcatalog',
            index=models.Index(fields=['preferred_label_en'], name='ai_escooccu_preferr_bb2717_idx'),
        ),
        migrations.AddIndex(
            model_name='escooccupationcatalog',
            index=models.Index(fields=['preferred_label_fr'], name='ai_escooccu_preferr_73a8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='escooccupationcatalog',
            index=models.Index(fields=['isco_group'], name='ai_escooccu_isco_gr_cec20d_idx'),
        ),
        migrations.AddField(
            model_name='escooccupationskillrelation',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='ai.escooccupationcatalog'),
        ),
        migrations.AddField(
            model_name='escooccupationskillrelation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_relations', to='ai.escoskill'),
        ),
        migrations.AddIndex(
            model_name='escooccupationskillrelation',
            index=models.Index(fields=['occupation', 'relation_type'], name='ai_escooccu_occupat_1734d8_idx'),
        ),
        migrations.AddIndex(
            model_name='escooccupationskillrelation',
            index=models.Index(fields=['skill', 'relation_type'], name='ai_escooccu_skill_i_a06f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='escooccupationskillrelation',
            index=models.Index(fields=['relation_type'], name='ai_escooccu_relatio_f3f0ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='escooccupationskillrelation',
            constraint=models.UniqueConstraint(fields=('occupation', 'skill', 'relation_type'), name='uniq_esco_occ_skill_relation'),
        ),
    ]
