# Generated by Django 5.0.6 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_escooccupationcatalog_escooccupationskillrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escooccupationcatalog',
            name='nace_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
