# Generated by Django 5.0.6 on 2026-05-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_escooccupationcatalog_nace_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidWiseSkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('normalized_key', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVIEW', 'Review'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidwise_aliases', to='ai.escoskill')),
            ],
            options={
                'ordering': ['alias', 'id'],
                'indexes': [models.Index(fields=['normalized_key', 'status'], name='ai_bidwises_normali_f85a5c_idx'), models.Index(fields=['target_skill', 'status'], name='ai_bidwises_target__403709_idx'), models.Index(fields=['language'], name='ai_bidwises_languag_934f88_idx')],
            },
        ),
    ]
