# Generated by Django 5.0.6 on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_bidwiseskillalias"),
        ("opportunities", "0033_opportunite_jobbert_embeddings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMHierarchyDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                ("profile_hash", models.CharField(db_index=True, max_length=64)),
                ("opportunity_content_hash", models.CharField(db_index=True, max_length=64)),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("is_compatible", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("issue", models.CharField(blank=True, default="unclear", max_length=32)),
                ("reason", models.CharField(blank=True, default="", max_length=280)),
                ("hierarchy_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_hierarchy_decisions",
                        to="opportunities.opportunite",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["profile_hash", "opportunity_content_hash"],
                        name="ai_llmhiera_profile_1997dc_idx",
                    ),
                    models.Index(
                        fields=["opportunity", "profile_hash"],
                        name="ai_llmhiera_opportu_ec1e75_idx",
                    ),
                    models.Index(fields=["provider", "model"], name="ai_llmhiera_provide_334ec5_idx"),
                    models.Index(
                        fields=["issue", "is_compatible"],
                        name="ai_llmhiera_issue_ba8727_idx",
                    ),
                ],
            },
        ),
    ]
