# Generated by Django 5.0.6 on 2026-05-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_llmhierarchydecision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidwiseskillalias',
            name='target_skill',
        ),
        migrations.DeleteModel(
            name='ESCOOccupation',
        ),
        migrations.RemoveField(
            model_name='escooccupationskillrelation',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='escooccupationskillrelation',
            name='skill',
        ),
        migrations.DeleteModel(
            name='BidWiseSkillAlias',
        ),
        migrations.DeleteModel(
            name='ESCOOccupationCatalog',
        ),
        migrations.DeleteModel(
            name='ESCOOccupationSkillRelation',
        ),
        migrations.DeleteModel(
            name='ESCOSkill',
        ),
    ]
