# Generated by Django 5.0.6 on 2026-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='annees_experience',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'années d'expérience (si applicable)", null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='competences',
            field=models.TextField(blank=True, help_text='Liste des compétences séparées par des virgules'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='domaines_interet',
            field=models.TextField(blank=True, help_text="Domaines d'intérêt (ex: web, IA, finance)"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='niveau_experience',
            field=models.CharField(blank=True, choices=[('DEBUTANT', 'Débutant (0–1 an)'), ('JUNIOR', 'Junior (1–3 ans)'), ('CONFIRME', 'Confirmé (3–5 ans)'), ('SENIOR', 'Senior (5+ ans)')], help_text="Niveau d'expérience pour le matching automatique", max_length=20),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
