# Generated by Django 5.0.6 on 2026-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='compensation_expectation',
            field=models.PositiveIntegerField(blank=True, help_text='Expected compensation amount', null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='compensation_period',
            field=models.CharField(blank=True, choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], help_text='Compensation period', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='employment_types',
            field=models.JSONField(blank=True, default=list, help_text="Desired employment types, e.g. ['FULL_TIME','CONTRACT']"),
        ),
        migrations.AddField(
            model_name='profil',
            name='last_onboarding_step',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last completed onboarding step (0-5)', null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='True after user completes onboarding wizard'),
        ),
        migrations.AddField(
            model_name='profil',
            name='opportunity_types',
            field=models.JSONField(blank=True, default=list, help_text="Target opportunity types, e.g. ['JOB','INTERNSHIP']"),
        ),
        migrations.AddField(
            model_name='profil',
            name='preferred_location',
            field=models.CharField(blank=True, help_text='Preferred city/region, free text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profile_visibility',
            field=models.BooleanField(default=True, help_text='Whether profile is discoverable by recruiters'),
        ),
        migrations.AddField(
            model_name='profil',
            name='remote_preference',
            field=models.CharField(blank=True, choices=[('ON_SITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], help_text='Remote work preference', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text="Target job titles/roles, e.g. ['Backend Developer','Data Engineer']"),
        ),
    ]
