# Generated by Django 5.0.6 on 2026-05-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_resume_semantic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='account_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('organization', 'Organization')], db_index=True, default='candidate', help_text='BidWise account type. Existing auth flows default to candidate.', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=180)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(max_length=16)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('startup', 'Startup'), ('public', 'Public'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_type'], name='org_profile_type_idx'), models.Index(fields=['created_at'], name='org_profile_created_idx')],
            },
        ),
    ]
