# Generated by Django 5.0.6 on 2026-05-11 01:52

import users.models
import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_utilisateur_account_type_organizationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileresume',
            name='file',
            field=models.FileField(blank=True, null=True, storage=users.storage.ProfileResumeStorage(), upload_to=users.models.profile_resume_upload_to),
        ),
    ]
