# Generated by Django 5.0.6 on 2026-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profileresume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='Account suspended by admin moderation.'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was suspended.', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='suspension_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('fraud', 'Fraud'), ('other', 'Other')], default='', help_text='Reason for suspension.', max_length=20),
        ),
    ]
