# Generated by Django 5.0.6 on 2026-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_utilisateur_is_suspended_utilisateur_suspended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Structured ESCO normalization results stored alongside legacy profile skills.'),
        ),
        migrations.AddField(
            model_name='profil',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='User-entered skill strings preserved before ESCO normalization.'),
        ),
        migrations.AddField(
            model_name='profil',
            name='skills_normalization_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profil',
            name='skills_normalization_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profil',
            name='skills_normalization_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileresume',
            name='extracted_normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Structured ESCO normalization results for extracted resume skill mentions.'),
        ),
        migrations.AddField(
            model_name='profileresume',
            name='extracted_raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='Raw semantic skill mentions extracted from the resume before ESCO normalization.'),
        ),
        migrations.AddField(
            model_name='profileresume',
            name='extracted_skills_normalization_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profileresume',
            name='extracted_skills_normalization_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profileresume',
            name='extracted_skills_normalization_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
