# Generated by Django 5.0.6 on 2026-05-15 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profil_normalized_skills_profil_raw_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUSPEND', 'Suspend user'), ('REACTIVATE', 'Reactivate user'), ('TOGGLE_ADMIN', 'Toggle admin privilege'), ('TOGGLE_ACTIVE', 'Toggle active status')], db_index=True, help_text='Type of admin action performed.', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Lightweight context: reason, detail, before/after values. Keep flat and minimal — not a general-purpose log store.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(help_text='Admin who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='User affected by the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='users_audit_actor_i_fea760_idx'), models.Index(fields=['target', '-created_at'], name='users_audit_target__807394_idx')],
            },
        ),
    ]
