# Generated by Django 5.0.6 on 2026-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profil_jobbert_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Reserved structured skill metadata. Kept empty by the current JobBERT/LLM pipeline.'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='User-entered skill strings preserved for recommendation features.'),
        ),
        migrations.AlterField(
            model_name='profileresume',
            name='extracted_normalized_skills',
            field=models.JSONField(blank=True, default=list, help_text='Reserved structured skill metadata. Kept empty by the current Qwen extraction pipeline.'),
        ),
        migrations.AlterField(
            model_name='profileresume',
            name='extracted_raw_skills',
            field=models.JSONField(blank=True, default=list, help_text='Raw semantic skill mentions extracted from the resume.'),
        ),
    ]
