# Generated by Django 5.0.6 on 2026-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_organizationprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='tender_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Calls-for-tender preferences: categories and optional max budget.'),
        ),
    ]
